version: '3.8'
services:
  influxdb:
    image: influxdb:2.7
    container_name: evc-grafana-influxdb-1
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb_data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_BUCKET=my-bucket
      - DOCKER_INFLUXDB_INIT_RETENTION=1w
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-token

  mosquitto:
    image: eclipse-mosquitto
    container_name: evc-grafana-mosquitto-1
    ports: ["1883:1883","9001:9001"]
    volumes:
      - ./mosquitto/config:/mosquitto/config

  telegraf:
    image: telegraf:1.28
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      mosquitto:
        condition: service_started
      influxdb:
        condition: service_started
    restart: always
    
  grafana:
    image: grafana/grafana:latest
    ports: ["3000:3000"]
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on: ["influxdb"]

volumes:
  influxdata:
